from flask import Flask, render_template, request, jsonify
import Task_2
import Task_3  

app = Flask(__name__)


# Index Route

# Serves the main HTML interface
@app.route('/')
def index():
    return render_template('interface.html')

def initialise_csv_files():
    """
    Ensures all node CSV files exist with a header row.
    Does not modify files that already exist and are correctly formatted.
    """
    node_files = ['InvA.csv', 'InvB.csv', 'InvC.csv', 'InvD.csv']
    header = "Item_ID,Item_QTY,Item_Price,Location\n"
    for filepath in node_files:
        try:
            with open(filepath, 'r') as f:
                content = f.read()
            # Only fix trailing newline if file has content but is missing it
            if content and not content.endswith('\n'):
                with open(filepath, 'a') as f:
                    f.write('\n')
        except FileNotFoundError:
            with open(filepath, 'w') as f:
                f.write(header)

# Task 1

# Handles sign and verify only, no consensus to demonstrate Task 1 in isolation
@app.route('/sign_and_verify', methods=['POST'])
def sign_and_verify():
    data = request.get_json()
    node_id = data['node_id']
    quantity = data['quantity']
    price = data['price']
    location = data['location']

    logs = []

    record = f"{Task_2.Task_1.iter_val}, {quantity}, {price}, {location}"
    logs.append(f"[RECORD] Created record: {record}")

    keys = Task_2.Task_1.get_node_keys(node_id)
    logs.append(f"[KEYS] Retrieved keys for Node {node_id}")
    logs.append(f"[KEYS] e = {keys['e']}")
    logs.append(f"[KEYS] n = {keys['n']}")

    hash_val = Task_2.Task_1.hash_record(record)
    logs.append(f"[HASH] MD5 hash of record: {hex(hash_val)}")

    signature = Task_2.Task_1.sign_record(record, keys['d'], keys['n'])
    logs.append(f"[SIGN] Signature generated by Node {node_id}: {hex(signature)}")

    verifications = {}
    for nid in ['A', 'B', 'C', 'D']:
        if nid != node_id:
            valid = Task_2.Task_1.verify_signature(record, signature, keys['e'], keys['n'])
            verifications[nid] = valid
            logs.append(f"[VERIFY] Node {nid} verified signature from Node {node_id}: {valid}")

    return jsonify({
        'record': record,
        'hash': hex(hash_val),
        'signature': hex(signature),
        'verifications': verifications,
        'logs': logs
    })


# Task 2

# Handles full process: sign -> verify -> BFT consensus -> store to demonstrate Task 1 and 2 together during marking
@app.route('/submit_record', methods=['POST'])
def submit_record():
    data = request.get_json()
    node_id = data['node_id']
    quantity = data['quantity']
    price = data['price']
    location = data['location']
    malicious_node = data.get('malicious_node', None)

    # Calls submit_record in Task_2 which runs the full pipeline
    # Returns record, hash, signature, per-node verifications, consensus votes and result
    result = Task_2.submit_record(node_id, quantity, price, location, malicious_node=malicious_node)
    return jsonify(result)


# Task 3

# Handles the full Part 2 query workflow:
# query -> each node signs -> multi-sig -> consensus check -> encrypt
@app.route('/query', methods=['POST'])
def query():
    data = request.get_json()
    item_id = int(data['item_id'])
    originator = data['originator']

    all_logs = []
    # Procurement Officer encrypts the item_id request with PKG's public key
    all_logs.append(f"[REQUEST] Procurement Officer initiating secure query for item {item_id}")
    encrypted_request = Task_3.RSA_encrypt(item_id, Task_3.PKG_n, Task_3.PKG_e)
    all_logs.append(f"[TRANSMIT] Encrypted query request sent to PKG: {encrypted_request['encrypted_message']}")
    all_logs.extend(encrypted_request['logs'])

    # PKG decrypts the request with its private key to recover the item_id
    all_logs.append(f"[PKG] PKG received encrypted request, decrypting with private key")
    decrypted_request = Task_3.RSA_decrypt(
        encrypted_request['encrypted_message'],
        Task_3.PKG_d,
        Task_3.PKG_n
    )
    all_logs.extend(decrypted_request['logs'])
    item_id = decrypted_request['plaintext']
    all_logs.append(f"[PKG] Recovered item_id: {item_id}")
    # Query the item from each node's CSV
    node_files = {
        'A': 'InvA.csv',
        'B': 'InvB.csv',
        'C': 'InvC.csv',
        'D': 'InvD.csv',
    }
    query_results = {}
    for node_id, filepath in node_files.items():
        result = Task_3.query_item(item_id, filepath)
        query_results[node_id] = result['record'].strip()
        all_logs.extend(result['logs'])

    # Use originating node's query result as message to sign
    message = int(query_results[originator].strip())
    all_logs.append(f"[MESSAGE] Value to be signed: {message}")

    # Each node signs message with their encrypted ID and random number
    node_params = {
        'A': {'encrypted_id': Task_3.Ag, 'rand_num': Task_3.Ar},
        'B': {'encrypted_id': Task_3.Bg, 'rand_num': Task_3.Br},
        'C': {'encrypted_id': Task_3.Cg, 'rand_num': Task_3.Cr},
        'D': {'encrypted_id': Task_3.Dg, 'rand_num': Task_3.Dr},
    }
    signatures = {}
    for node_id, params in node_params.items():
        sig_result = Task_3.sign_message(
            message,
            params['encrypted_id'],
            params['rand_num'],
            Task_3.PKG_n,
            node_id
        )
        signatures[node_id] = sig_result['signature']
        all_logs.extend(sig_result['logs'])

    # Compute multi-signature
    multi_result = Task_3.multi_sig_msg(
        signatures['A'],
        signatures['B'],
        signatures['C'],
        signatures['D'],
        Task_3.PKG_n,
        originator
    )
    all_logs.extend(multi_result['logs'])

    # Each node independently computes multi-sig, then confirm they all match
    node_multisigs = {}
    for node_id, params in node_params.items():
        node_multi = Task_3.multi_sig_msg(
            signatures['A'],
            signatures['B'],
            signatures['C'],
            signatures['D'],
            Task_3.PKG_n,
            node_id
        )
        node_multisigs[node_id] = node_multi['multisig']

    consensus_result = Task_3.confirm_consensus(
        node_multisigs['A'],
        node_multisigs['B'],
        node_multisigs['C'],
        node_multisigs['D'],
        originator
    )
    all_logs.extend(consensus_result['logs'])

    # Verify the multi-signature using PKG public key
    hashed_message = Task_3.hash_record(str(Task_3.t_key) + str(message))
    verify_result = Task_3.verify_signature(multi_result['multisig'], hashed_message)
    all_logs.extend(verify_result['logs'])

    # Encrypt the result using Procurement Officer's public key
    encrypt_result = Task_3.RSA_encrypt(message, Task_3.POn, Task_3.POe)
    all_logs.extend(encrypt_result['logs'])

    # Procurement Officer decrypts the result
    decrypt_result = Task_3.RSA_decrypt(
        encrypt_result['encrypted_message'],
        Task_3.POd,
        Task_3.POn
    )
    all_logs.extend(decrypt_result['logs'])

    return jsonify({
        'query_results': query_results,
        'message': message,
        'signatures': {k: hex(v) for k, v in signatures.items()},
        'multi_sig': hex(multi_result['multisig']),
        'consensus': {
            'verdict': consensus_result.get('verdict') or consensus_result.get('Verdict'),
            'A_sig': hex(consensus_result['A_sig']),
            'B_sig': hex(consensus_result['B_sig']),
            'C_sig': hex(consensus_result['C_sig']),
            'D_sig': hex(consensus_result['D_sig']),
        },
        'verify': {
            'first_half': hex(verify_result['first_half']),
            'second_half': hex(verify_result['second_half']),
        },
        'encrypted_result': hex(encrypt_result['encrypted_message']),
        'decrypted_result': decrypt_result['plaintext'],
        'logs': all_logs
    })

# Main implementation

if __name__ == '__main__':
    """To open the website, run this file and navigate to http://localhost:5000"""
    initialise_csv_files()
    app.run(debug=True)