import Task_1
import Task_2


 # Initialising the cryptographic components



 # Procurement Officer's cryptographic components
PO_p = 1080954735722463992988394149602856332100628417
PO_q = 1158106283320086444890911863299879973542293243
PO_e = 106506253943651610547613
 # derived Procurement Officer cryptographic components
PO_n = PO_p * PO_q
PO_phi_n = (PO_p-1) * (PO_q-1)
PO_d = pow(PO_e, -1, PO_n)

 # PKG cryptographic Parameters.
PKG_p = 1004162036461488639338597000466705179253226703
PKG_q = 950133741151267522116252385927940618264103623
PKG_e = 973028207197278907211
 # Derived Procurement Officer cryptographic components
PKG_n = PKG_p * PKG_q
PKG_phi_n = (PKG_p -1) * (PKG_q -1)
PKG_d = pow(PKG_e, -1, PKG_n)

 # initialising warehouse ID for PKG to use to generate the secret key for each signer
A_i = 126
B_i= 127
C_i = 128
D_i = 129

 # Derived secret keys from warehouse IDs generated by PKG
A_secret_key = pow(A_rand_num, PKG_d, PKG_n)
B_secret_key = pow(B_rand_num, PKG_d, PKG_n)
C_secret_key = pow(C_rand_num, PKG_d, PKG_n)
D_secret_key = pow(D_rand_num, PKG_d, PKG_n)


 # initialising random number selected by each warehouse
A_r = 621
B_r = 721
C_r = 821
D_r = 921

 # derived encrypted random numbers
A_er = pow(A_er, PKG_e, PKG_n)
B_er = pow(B_er, PKG_e, PKG_n)
C_er = pow(C_er, PKG_e, PKG_n)
D_er = pow(D_er, PKG_e, PKG_n)


 # initialising the combined secret key (MIGHT BE THE SHARED SIGNATURE????)
t_key = pow((A_secret_key * B_secret_key * C_secret_key * D_secret_key),1, PKG_n)



 # Implement a mechanism that allows an authorised external user to submit a query request to the
 # distributed inventory system.

 # List containing authenticated user public key component {temporary}
auth_user_lst = (PO_n)


 # authorised user enters an identifier and the id of the item they wish to search for.
def auth_user_search(user_sig, search_id):


 # verification, may not be necessary
def verify_user_auth(user_sig):



 # encrypting search results. {may not be necessary}

def encrypt_search(result, public_key):


# TODO: either use hash method from previous task or create new hash method and call inside of below function
# TODO: message hasn't been hashed yet, this will exclusively be a test format, full implementation after skeleton

def sign_message(message, secret_key, rand_num, n):

    signature = pow((secret_key * rand_num), message, n)

    return signature
""" Just a general note that the above sign_message method may function better in html if is a print instead of return
    if that turns out to be the case, feel free to switch it, William.
    
    Additional note for html implementation: call this function 4 times, once for each inventory signature,
    I'll leave an example of which variables to use below, 
"""


 # Calculates multisignature using the
def multi_sig_msg(sig_1, sig_2, sig_3, sig_4, n):
    final_sig = pow((sig_1 * sig_2 * sig_3 * sig_4),1, n)
    return final_sig


 # TODO: URGENT create input tuple and make sure it returns message, signature, and multisig public component t.

 # validates the
def multi_sig_validation(sig_1, sig_2, sig_3, sig4, multi_sig, e, n):
    result = pow(s, e, n)
    return result

""" Below is code test running the math, feel free to ignore, but delete before submission {temporary}"""
a_sig = sign_message(a)
b_sig = sign_message(b)
c_sig = sign_message(c)
d_sig = sign_message(d)
multi_sig = multi_sig_msg(fill_later)

multi_sig_validation(a_sig, b_sig, c_sig, d_sig, multi_sig, PKG_e, PKG_n)


