import Task_1

# Byzantine Fault Tolerant consensus - chosen because the scenario requires handling
# malicious/inconsistent nodes, not just crashes. With 4 nodes, system tolerates 1 byzantine
# node and requires 3/4 agreement to accept a record.


def simulate_node_verification(record, signature, originator_id):
    """
    Each node independently verifies signature using originator's public key.
    Returns True/False representing that node's vote.
    """
    keys = Task_1.get_node_keys(originator_id)
    return Task_1.verify_signature(record, signature, keys['e'], keys['n'])


def bft_consensus(record, signature, originator_id, malicious_node=None):
    """
    Simplified BFT consensus round.
    Each non-originating node verifies the record signature and casts a vote.
    Consensus passes if >= 3 of 4 nodes approve (tolerates 1 byzantine node).
    malicious_node: if set, that node will cast a False vote regardless of signature validity.
    Returns a dict with each node's vote, logs, and the final consensus result.
    """
    nodes = ['A', 'B', 'C', 'D']
    votes = {}
    logs = []

    logs.append(f"[CONSENSUS] Starting BFT consensus round for record: {record}")
    logs.append(f"[CONSENSUS] Originating node: {originator_id}")
    logs.append(f"[CONSENSUS] Malicious node: {malicious_node if malicious_node else 'None'}")
    logs.append(f"[CONSENSUS] Threshold: 3/4 nodes must approve")

    for node_id in nodes:
        if node_id == originator_id:
            votes[node_id] = True
            logs.append(f"[NODE {node_id}] Originator — auto-vote: True")
        elif node_id == malicious_node:
            votes[node_id] = False
            logs.append(f"[NODE {node_id}] MALICIOUS — forced vote: False")
        else:
            result = simulate_node_verification(record, signature, originator_id)
            votes[node_id] = result
            logs.append(f"[NODE {node_id}] Verified signature — vote: {result}")

    approvals = sum(votes.values())
    threshold = 3
    consensus_reached = approvals >= threshold

    logs.append(f"[CONSENSUS] Approvals: {approvals}/4")
    logs.append(f"[CONSENSUS] Result: {'ACCEPTED' if consensus_reached else 'REJECTED'}")

    return {
        'votes': votes,
        'approvals': approvals,
        'threshold': threshold,
        'consensus_reached': consensus_reached,
        'logs': logs
    }


def store_to_all_nodes(record, logs):
    """
    After consensus, store accepted record to every node's local CSV.
    """
    node_files = {
        'A': r'InvA.csv',
        'B': r'InvB.csv',
        'C': r'InvC.csv',
        'D': r'InvD.csv',
    }
    for node_id, filepath in node_files.items():
        Task_1.add_record(filepath, record + '\n')
        logs.append(f"[STORAGE] Record written to Node {node_id} ({filepath})")


def submit_record(node_id, quantity, price, location, malicious_node=None):
    """
    Full Task 1 + 2 lifecycle: create -> sign -> verify -> consensus -> store
    Returns a dict the frontend can display at each step including logs.
    """
    logs = []

    # Create the record string
    record = f"{Task_1.iter_val}, {quantity}, {price}, {location}"
    logs.append(f"[RECORD] Created record: {record}")

    # Get originating node's keys
    keys = Task_1.get_node_keys(node_id)
    logs.append(f"[KEYS] Retrieved keys for Node {node_id}")
    logs.append(f"[KEYS] e = {keys['e']}")
    logs.append(f"[KEYS] n = {keys['n']}")

    # Hash the record
    hash_val = Task_1.hash_record(record)
    logs.append(f"[HASH] MD5 hash of record: {hex(hash_val)}")

    # Sign with originating node's private key
    signature = Task_1.sign_record(record, keys['d'], keys['n'])
    logs.append(f"[SIGN] Signature generated by Node {node_id}: {hex(signature)}")

    # Each other node verifies with originator's public key
    verification_results = {}
    for nid in ['A', 'B', 'C', 'D']:
        if nid != node_id:
            valid = Task_1.verify_signature(record, signature, keys['e'], keys['n'])
            verification_results[nid] = valid
            logs.append(f"[VERIFY] Node {nid} verified signature from Node {node_id}: {valid}")

    # BFT consensus round, passing malicious_node if set
    consensus = bft_consensus(record, signature, node_id, malicious_node=malicious_node)
    logs.extend(consensus['logs'])

    # Store to all nodes if consensus passed
    if consensus['consensus_reached']:
        store_to_all_nodes(record, logs)
        Task_1.iterate_id()
        logs.append(f"[RECORD] iter_val incremented to {Task_1.iter_val}")
    else:
        logs.append(f"[RECORD] Consensus failed — record not stored")

    return {
        'record': record,
        'hash': hex(hash_val),
        'signature': hex(signature),
        'verifications': verification_results,
        'consensus': {
            'votes': consensus['votes'],
            'approvals': consensus['approvals'],
            'threshold': consensus['threshold'],
            'consensus_reached': consensus['consensus_reached']
        },
        'accepted': consensus['consensus_reached'],
        'logs': logs
    }
